email-server: "smtp.svc.pivotal.io"
email-from: "ci@spring.io"
email-to: ["spring-boot-dev@pivotal.io"]
github-repo: "https://github.com/snicoll/spring-boot.git"
github-repo-name: "spring-projects/spring-boot"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "gh-16970"
build-name: "spring-boot"
pipeline-name: "spring-boot"
concourse-url: "https://ci.spring.io"
bintray-subject: "spring"
bintray-repo: "jars"
